config/routes.rb
Rails.application.routes.draw do

  resources :orders, :only => [:index] do

  end

  root "orders#index"

  get '/orders/starclick' => 'orders#starclick', as: 'starclick'
  get '/orders/download' => 'orders#download', as: 'downloadpi'

  get '/assurance' => 'assurances#index', as: 'assurance'
  get '/assurance/download' => 'assurances#download', as: 'downloadggn'
  

end

app/views/dashboards/_dashboard_assurance_dcs.html.erb
<div id="dashboard3" class="row">
	<div class="col-md-12">
	<h2 align="center">Dashboard Assurance</h2>
	<br>
		<h4 align="center">GPON</h3>
		<table class="dashboard-table" border="1">
			<thead bgcolor='red'>
				<td>AREA</td>
				<td>STO</td>
				<td>< 1</td>
				<td>2 - 3</td>
				<td>4 - 7</td>
				<td>8 - 15</td>
				<td>16 - 30</td>
				<td>30 > </td>
				<td>TOTAL</td>
			</thead>
			<tbody>
			<% @datel.each do |x| %>
				
				<% case x %>
				<% when 'PLK' %>
				<% sto = ['PLK','KM5','PYM','KKN','PPS'] %>
				<td rowspan=<%= sto.count+1 %> bgcolor='orange' >PLK</td>
				<% when "PBU" %>
				<% sto = ["PBU","KPA","SUA","KMI"] %>
				<td rowspan=<%= sto.count+1 %> bgcolor='lightblue' >PBU</td>
				<% when "SAI" %>
				<% sto = ["SAD","SAI","SPT"] %>
				<td rowspan=<%= sto.count+1 %> bgcolor='orange' >SAI</td>
				<% when "MTW" %>
				<% sto = ["MTW","TML","PRC"] %>
				<td rowspan=<%= sto.count+1 %> bgcolor='lightblue' >MTW</td>
				<% when "???" %>
				<% sto = ["PTZ","NEG"] %>
				<td rowspan=<%= sto.count+1 %> bgcolor='orange' >???</td>
				<% else %>
				<% sto = nil %>
				<td rowspan=<%= sto.count+1 %> bgcolor='lightblue' >-</td>
				<% end %>
				<% sto.each do |stox| %>				
				<tr>

					<% query_gpon = "clid like ? OR clid like ? OR node_id like ? OR node_id like ? OR headline like ? OR headline like ? OR headline like ?", "09%","GP%","09%","GP%","09%","GP%","%ODP%" %>
					<% query_cust = "type_cust like ? OR type_cust like ? OR type_cust like ? OR type_cust like ?", "%SILVER%","%GOLD%","%TITANIUM%","%PLATINUM%"%>
					<% query_sto = "sto like ?", "%#{stox}%"%>
					<% query = Nonatero.where(witel: 'KALTENG').where(query_sto).where(query_gpon).where(query_cust) %>

					<td><%= stox %></td>
					<td><%= link_to query.where(hari: 0..1).count, downloadggn_url(format: "xls", query: "GPON < 1", datel: stox) %></td>
					<td><%= link_to query.where(hari: 1..3).count, downloadggn_url(format: "xls", query: "GPON 2 - 3", datel: stox) %></td>
					<td><%= link_to query.where(hari: 3..7).count, downloadggn_url(format: "xls", query: "GPON 4 - 7", datel: stox) %></td>
					<td><%= link_to query.where(hari: 7..15).count, downloadggn_url(format: "xls", query: "GPON 8 - 15", datel: stox) %></td>
					<td><%= link_to query.where(hari: 15..30).count, downloadggn_url(format: "xls", query: "GPON 16 - 30", datel: stox) %></td>
					<td><%= link_to query.where.not(hari: 0..30).count, downloadggn_url(format: "xls", query: "GPON 30 >", datel: stox) %></td>
					<td><%= link_to query.count, downloadggn_url(format: "xls", query: "GPON", datel: stox) %></td>
				</tr>
				<% end %>
			<% end %>
			</tbody>
		</table>
		<br>
		<br>


		<h4 align="center">COOPER</h3>
		<table class="dashboard-table" border="1">
			<thead bgcolor='red'>
				<td>AREA</td>
				<td>STO</td>
				<td>< 1</td>
				<td>2 - 3</td>
				<td>4 - 7</td>
				<td>8 - 15</td>
				<td>16 - 30</td>
				<td>30 > </td>
				<td>TOTAL</td>
			</thead>
			<tbody>
			<% @datel.each do |x| %>
				
				<% case x %>
				<% when 'PLK' %>
				<% sto = ['PLK','KM5','PYM','KKN','PPS'] %>
				<td rowspan=<%= sto.count+1 %> bgcolor='orange' >PLK</td>
				<% when "PBU" %>
				<% sto = ["PBU","KPA","SUA","KMI"] %>
				<td rowspan=<%= sto.count+1 %> bgcolor='lightblue' >PBU</td>
				<% when "SAI" %>
				<% sto = ["SAD","SAI","SPT"] %>
				<td rowspan=<%= sto.count+1 %> bgcolor='orange' >SAI</td>
				<% when "MTW" %>
				<% sto = ["MTW","TML","PRC"] %>
				<td rowspan=<%= sto.count+1 %> bgcolor='lightblue' >MTW</td>
				<% when "???" %>
				<% sto = ["PTZ","NEG"] %>
				<td rowspan=<%= sto.count+1 %> bgcolor='orange' >???</td>
				<% else %>
				<% sto = nil %>
				<td rowspan=<%= sto.count+1 %> bgcolor='lightblue' >-</td>
				<% end %>
				<% sto.each do |stox| %>				
				<tr>

					<% query_cooper = "clid like ? OR clid like ? OR clid like ? OR node_id like ? OR node_id like ? OR node_id like ? OR headline like ? OR headline like ? OR headline like ?", "COO%","MSA%","DSLA%","COO%","MSA%","DSLA%","COO%","MSA%","DSLA%" %>
					<% query_cust = "type_cust like ? OR type_cust like ? OR type_cust like ? OR type_cust like ?", "%SILVER%","%GOLD%","%TITANIUM%","%PLATINUM%"%>
					<% query_sto = "sto like ?", "%#{stox}%"%>
					<% query = Nonatero.where(witel: 'KALTENG').where(query_sto).where(query_cooper).where(query_cust) %>

					<td><%= stox %></td>
					<td><%= link_to query.where(hari: 0..1).count, downloadggn_url(format: "xls", query: "COOPER < 1", datel: stox) %></td>
					<td><%= link_to query.where(hari: 1..3).count, downloadggn_url(format: "xls", query: "COOPER 2 - 3 ", datel: stox) %></td>
					<td><%= link_to query.where(hari: 3..7).count, downloadggn_url(format: "xls", query: "COOPER 4 - 7", datel: stox) %></td>
					<td><%= link_to query.where(hari: 7..15).count, downloadggn_url(format: "xls", query: "COOPER 8 - 15", datel: stox) %></td>
					<td><%= link_to query.where(hari: 15..30).count, downloadggn_url(format: "xls", query: "COOPER 16 - 30", datel: stox) %></td>
					<td><%= link_to query.where.not(hari: 0..30).count, downloadggn_url(format: "xls", query: "COOPER 30 >", datel: stox) %></td>
					<td><%= link_to query.count, downloadggn_url(format: "xls", query: "COOPER", datel: stox) %></td>
				</tr>
				<% end %>
			<% end %>
			</tbody>
		</table>

	</div>	
</div>

app/views/dashboards/_dashboard_pi.html.erb
<div id="dashboard2" class="row">
	<div class="col-md-12">
	<h2 align="center">Dashboard PI</h2>
		<table class="dashboard-table" border="1">
			<thead bgcolor="red">
				<tr> 
					<th rowspan="3">Area</th>
					<th rowspan="3">Total Inputan HI</th>
					<th rowspan="3">Total Inputan Masuk MS2N</th>
					<th colspan="3">Provision Issued</th>
					<th rowspan="3">Activation Completed</th>
				</tr>
				<tr>
					<th rowspan="2">HI > </th>
					<th rowspan="2">HI</th>
					<th rowspan="2">Grand Total</th>
				</tr>
			</thead>
			<tbody>
				<% if @sto == nil %>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				<% else %>
					<% @sto.each do |datel|%>
					<% today = Date.today %>
					<tr>
						<% case datel %>
						<% when ['KKN','KKP','PLK','PPS','PYM'] %>
						<td bgcolor="orange"> PLK </td>
						<% when ['KMI','SUA','PBU'] %>
						<td bgcolor="orange"> PBU </td>
						<% when ['KPB','SAI'] %>
						<td bgcolor="orange"> SAI </td>
						<% when ['AMP','PRC','BNT','TML','MTW'] %>
						<td bgcolor="orange"> MTW </td>
						<% when ['KKN','KKP','PLK','PPS','PYM','KMI','SUA','PBU','KPB','SAI','AMP','PRC','BNT','TML','MTW'] %>
						<td bgcolor="lightblue"> TOTAL </td>
						<% else %>			
						<td><%= datel %></td>
						<% end %>
						<td><%= link_to Order.where("orderdate like ?", "%#{today}%").where(sto: datel).where.not("status in ('CANCEL COMPLETED','Cancel Order')").count, downloadpi_url(format: "xls", query: "totalInputHI", datel: datel) %></td>

						<td><%= link_to Order.where("orderdate like ?", "%#{today}%").where(sto: datel).where(status_va: "VA").count, downloadpi_url(format: "xls", query: "totalInputMS2NHI", datel: datel) %></td>

						<td><%= link_to Order.where.not("orderdate like ?", "%#{today}%").where(sto: datel).where(status_va: "VA").where(status: "Process OSS (Provision Issued)").count, downloadpi_url(format: "xls", query: "PI>HI", datel: datel) %></td>

						<td><%= link_to Order.where("orderdate like ?", "%#{today}%").where(sto: datel).where(status_va: "VA").where(status: "Process OSS (Provision Issued)").count, downloadpi_url(format: "xls", query: "PIHI", datel: datel) %></td>

						<td><%= link_to Order.where(sto: datel).where(status_va: "VA").where(status: "Process OSS (Provision Issued)").count, downloadpi_url(format: "xls", query: "grandTotal", datel: datel) %></td>

						<td><%= link_to Order.where(sto: datel).where(status_va: "VA").where(status: "Process OSS (Activation Completed)").count, downloadpi_url(format: "xls", query: "AC", datel: datel) %></td>
					</tr>
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>	
</div>

app/views/dashboards/_dashboard_psb.html.erb
<div id="dashboard1" class="row">	
	<h2 align="center">Dashboard PSB</h2>
	<% @statuses.each do |status| %>
		<div class="col-md-4">
			<div>
				<p>
					<span>
						<%= status %><br>					
					</span>
					<span>
						3P: <%= Order.where(status: status).where(status_va: "VA").count %><br>
						Non 3P: <%= Order.where(status: status).where(status_va: nil).count %>
					</span>
				</p>
			</div>
		</div>	
	<% end %>
</div>